# Generated by Django 3.2.15 on 2022-08-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=128)),
                ('chinese_word', models.CharField(max_length=256)),
                ('list', models.IntegerField()),
            ],
        ),
    ]
