# Generated by Django 3.2.15 on 2022-08-06 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word_home', '0002_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='word_home.book'),
        ),
    ]
