# Generated by Django 3.2.15 on 2022-08-06 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word_home', '0003_word_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_word', to='word_home.book'),
        ),
    ]
