# Generated by Django 3.2.15 on 2022-08-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_home', '0004_alter_word_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='page',
            field=models.IntegerField(default=0),
        ),
    ]
